name: My YourTomo cat
on:
  schedule:
    - cron: '23 */6 * * *' # every 6 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  pet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prsdx/github-pet@v1
        with:
          username: pragati-singhal
          timezone-offset-minutes: "330"
          accent-color: "#b30000"
